# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  # UnitTest,UITestとバグ・脆弱性の解析
  desc "Execute Test"
  lane :test do
    scan(
	scheme: "Limit"
    )
    sonar(
	project_key: "maniCreate_Limit",
 	project_version: "1.0",
 	project_name: "Limit",
 	sources_path: File.expand_path("../Limit"),
	sonar_login: "cb008312207a1ede1db4d09bdb88aff6088e9715"
    )
  end
  
  # リリース前のベータ版テスト,Deploygateへビルド
  desc "Build beta version before release"
  lane :beta_build_inhouse do
    
  end

  # AppStoreへアプリ配布
  desc "Push to AppStore"
  lane :deploy do
    # Import certificates

    # Download provisioning profiles

    # Build

    # Push to Crashlytics

  end


end
